print("-----------------------------------------------------------")
numero = int(input("Digite um número para saber a sua tabuda:"))
print("-----------------------------------------------------------")
print(f'-                 A tabuada do número {numero} é {1*numero}')
print(f'-                 A tabuada do número {numero} é {2*numero}')
print(f'-                 A tabuada do número {numero} é {3*numero}')
print(f'-                 A tabuada do número {numero} é {4*numero}')
print(f'-                 A tabuada do número {numero} é {5*numero}')
print(f'-                 A tabuada do número {numero} é {6*numero}')
print(f'-                 A tabuada do número {numero} é {7*numero}')
print(f'-                 A tabuada do número {numero} é {8*numero}')
print(f'-                 A tabuada do número {numero} é {9*numero}')
print(f'-                 A tabuada do número {numero} é {10*numero}')
print("------------------------------------------------------------")
